import Head from "next/head";
import Image from "next/image";
import Card from "../Components/Card";
import Hero from "../Components/Hero";
import styles from "../styles/Home.module.css";

import COFFEE_STORES from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: { COFFEE_STORES }
  }
}

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        buttonText={"View stores nearby"}
        handleOnClick={() => {
          console.log("click");
        }}
      />
      {props.COFFEE_STORES && <>
        {props.COFFEE_STORES.length > 0 ? <h2 className={styles.header}>Toronto stores</h2> : null}

        <div className={styles.layout}>
          {props.COFFEE_STORES.map((coffee) => {
            return (
              <Card
                key={coffee.id}
                className={styles.card}
                storeName={coffee.name}
                imgUrl={coffee.imgUrl}
                href={`/coffee-store/${coffee.id}`}
              />
            );
          })}
        </div>
      </>}

      <footer className={styles.footer}></footer>
    </div>
  );
}
