import { useEffect, useState } from "react";

import Head from "next/head";
import Card from "../Components/Card";
import Hero from "../Components/Hero";
import styles from "../styles/Home.module.css";

import COFFEE_STORES from "../data/coffee-stores.json";
import { fetchCoffeeStores, fetchImage } from "../lib/coffee-stores";
import useTrackLocation from "../hooks/use-track-location";

const fetchData = async () => {
  try {
    const data = await fetchCoffeeStores();
    const transformedData = data?.results?.map((venue) => {
      return {
        id: venue.fsq_id,
        ...venue
      }
    }) || [];

    return transformedData || COFFEE_STORES;

  }
  catch (error) {
    console.error(error)
  }
}

export async function getStaticProps() {
  const data = await fetchData() || COFFEE_STORES;

  const endData = await Promise.all(data.map(async (venue, key) => {
    const photos = await fetchImage();
    const imgUrl = photos[key]
    return {
      ...venue,
      imgUrl
    }
  }));

  return {
    props: { COFFEE_STORES: endData }
  }
}

export default function Home(props) {
  const [coffeeStores, setCoffeeStores] = useState(props.COFFEE_STORES);
  const { handleTrackLocation, errorMessage, latLong, isFindingLocation } = useTrackLocation();

  useEffect(() => {
    async function fetchData() {
      if (latLong) {
        try {
          const coffeeStores = await fetchCoffeeStores(latLong);
          setCoffeeStores(coffeeStores);
        }
        catch (error) {

        }
      }
    }

    fetchData();
  }, [latLong])

  const handleClick = () => {
    handleTrackLocation();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        buttonText={isFindingLocation ? 'Locating...' : "View stores nearby"}
        handleOnClick={handleClick}
        hasError={!!errorMessage}
        errorMessage={errorMessage}
      />
      {coffeeStores && <>
        {coffeeStores.length > 0 ? <h2 className={styles.header}>Toronto stores</h2> : null}

        <div className={styles.layout}>
          {coffeeStores.map((coffee) => {
            return (
              <Card
                key={coffee.id}
                className={styles.card}
                storeName={coffee.name}
                imgUrl={coffee.imgUrl ?? 'https://images.unsplash.com/photo-1498804103079-a6351b050096?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2468&q=80'}
                href={`/coffee-store/${coffee.id}`}
              />
            );
          })}
        </div>
      </>}

      <footer className={styles.footer}></footer>
    </div>
  );
}
